### ISSUE TITLE
Issue with internal temperature reported in HomeKit being stuck at 22 degrees

### ISSUE THREAD

**Issue by dbonyad** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#380] opened 2024-06-23 22:31 UTC
Hi,

I’m seeing small bug with the platform in that sometimes the internal measured temperature shown in HomeKit is wrong. It seems to keep going to 22 degrees intermittently, even when that is not the measured temperature.

The internal temperature reading is always correct in the comfort cloud app, and it is sometimes correct in HomeKit. However randomly it seems to go from the actual value to 22 degrees in HomeKit for some reason. With my AC, the internal temperature is always reported even if it is switched off.

Note this has no effect on the set point temperature, this works perfectly, it’s only the internal measured temperature that is sometimes wrong. 

Please see some logs of the issue below. Note that the AC is on this whole time and the settings have not changed at all when it switches to 22 degrees at 23:03:10.

[23/06/2024, 22:55:00] [Homebridge Panasonic AC Platform] Hallway: set On
[23/06/2024, 22:55:08] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 18, Outdoor Temp. 21, Cool Mode, Speed 5 (Powerful Mode).
[23/06/2024, 22:57:00] [Homebridge Panasonic AC Platform] Hallway: set On
[23/06/2024, 22:57:08] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 18, Outdoor Temp. 20, Cool Mode, Speed 5 (Powerful Mode).
[23/06/2024, 22:59:00] [Homebridge Panasonic AC Platform] Hallway: set On
[23/06/2024, 22:59:09] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 18, Outdoor Temp. 20, Cool Mode, Speed 5 (Powerful Mode).
[23/06/2024, 23:01:01] [Homebridge Panasonic AC Platform] Hallway: set On
[23/06/2024, 23:01:09] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 18, Outdoor Temp. 20, Cool Mode, Speed 5 (Powerful Mode).
[23/06/2024, 23:03:01] [Homebridge Panasonic AC Platform] Hallway: set On
[23/06/2024, 23:03:10] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 22, Outdoor Temp. not available, Cool Mode, Speed 5 (Powerful Mode).

**Comment by mkz212** [comment] 2024-06-24 02:10
Hmm. We tested it for quite a long time and had no problems with the temperature. I am unable to reproduce to such a situation. I need more data to be able to take care of it.

- is this your only air conditioning? and if not, does the problem appear only on it?

- does it occur in any specific situations?

**Comment by dbonyad** [comment] 2024-06-24 09:14
Hello,

Unfortunately I only have one AC unit so I'm unable to test if it's an issue on others.

I have checked the Panasonic comfort cloud app historical temperature data. At no point does the indoor temperature ever go to 22 degrees. 

In the logs it seems to match with the outdoor temperature going unavailable, even though the outdoor temperature is still visible in the comfort cloud app.





[24/06/2024, 10:02:23] [Homebridge Panasonic AC Platform] Hallway: Off, Indoor Temp. 22, Outdoor Temp. not available, Cool Mode, Speed 5.
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Accessory: setTargetHeaterCoolerState() for device 'Hallway'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: Mode Cool
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Comfort Cloud: sendUpdate() for 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] {
  "operate": 1,
  "operationMode": 2
}
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Accessory: setActive() for device 'Hallway'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: set On
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Comfort Cloud: sendUpdate() for 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] {
  "operate": 1
}
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: On
[24/06/2024, 10:02:54] [Homebridge Panasonic AC Platform] Comfort Cloud - setDeviceStatus(): Success
[24/06/2024, 10:02:54] [Homebridge Panasonic AC Platform] { result: 0 }
[24/06/2024, 10:02:55] [Homebridge Panasonic AC Platform] Comfort Cloud - setDeviceStatus(): Success
[24/06/2024, 10:02:55] [Homebridge Panasonic AC Platform] { result: 0 }
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Hallway: refresh status
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Comfort Cloud: getDeviceStatus() for device GUID 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for GUID 'CS-Z35XKEW+4886927481': Success
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] {
  timestamp: 1719219776059,
  permission: 3,
  summerHouse: 0,
  iAutoX: false,
  nanoe: true,
  nanoeStandAlone: true,
  autoMode: true,
  heatMode: true,
  fanMode: false,
  dryMode: true,
  coolMode: true,
  ecoNavi: false,
  powerfulMode: true,
  quietMode: true,
  airSwingLR: true,
  autoSwingUD: true,
  ecoFunction: 0,
  temperatureUnit: 0,
  modeAvlList: { autoMode: 1 },
  nanoeList: { visualizationShow: 0 },
  clothesDrying: false,
  insideCleaning: false,
  fireplace: false,
  pairedFlg: false,
  parameters: {
    operate: 1,
    operationMode: 2,
    temperatureSet: 16,
    fanSpeed: 5,
    fanAutoMode: 0,
    airSwingLR: 2,
    airSwingUD: 2,
    ecoMode: 0,
    ecoNavi: 0,
    nanoe: 2,
    lastSettingMode: 0,
    iAuto: 0,
    airDirection: 0,
    insideTemperature: 22,
    outTemperature: 126,
    airQuality: 0,
    ecoFunctionData: 0,
    insideCleaning: 0,
    fireplace: 0
  },
  deviceNanoe: 2,
  visualizationAvlFlg: true,
  simulationShowFlg: true,
  simulationSettingFlg: false
}
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 22, Outdoor Temp. not available, Cool Mode, Speed 5.

**Comment by mkz212** [comment] 2024-06-24 09:30
We get inside temperature from response from server. You can see in your log that `insideTemperature: 22,`. So it is something wrong with Comfort Cloud.

**Comment by dbonyad** [comment] 2024-06-24 09:40
Ok no worries, to be honest it's quite a minor issue, I just I'd raise as sometimes it's confusing seeing the wrong temperature in Homekit.

Do you know why the correct temperature would be shown in the Comfort Cloud app, even if the server is transmitting the wrong temperature.

![image](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/61993882/163dc241-4715-4e28-bebb-9d815562a6ed)

**Comment by mkz212** [comment] 2024-06-24 09:43
Cause in CC app values are refreshed not so often as in plugin. In CC app every hour, in plugin every 10 minutes when AC is on and every 60 minutes when off. And apparently it just didn't hit the wrong value in CC app.

**Comment by mkz212** [comment] 2024-06-24 11:08
I'm closing because it's most likely something on the Comfort Cloud side. We have no influence on what we receive from the server.

**Closed by mkz212** 2024-06-24 11:08 UTC
