### ISSUE TITLE
Request failed with status code 412

### ISSUE THREAD

**Issue by Luca-Lusu** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#525] opened 2024-11-05 06:22 UTC
### Description

Starting from November 4th, Panasonic Cloud Servers are refusing my login with 412 error.
Everyting seems fine: MFA was configured and working (until yesterday), Panasonic App works correctly. 
Are you having the same issue? Suspect is that Panasonic did it again...
Luca

### Plugin version

v5.2.1

**Comment by Pierrefogg** [comment] 2024-11-05 06:36
Wtf is Panasonic problem???? They of course are totally aware they are fucking with peoples lives - and the developers at Panasonic probably think this is funny

**Comment by mkz212** [comment] 2024-11-05 07:07
This would not be the first time Panasonic has changed the API. Unfortunately, some manufacturers (such as Gree) offer local access and nothing changes there and plugins have been working without a problem for years. With Panasonic, connection is thru Panasonic server and this is a constant battle.

**Comment by mkz212** [comment] 2024-11-05 07:25
Home Assistant integration also stops working today about 2 am. 

Expected status code 200, received: 412: {
  "code":41201,
  "message":"Precondition Failed"
}

**Comment by ajimix** [comment] 2024-11-05 13:06
Same problem for me, started few hours ago

**Comment by ChristianPorsche** [comment] 2024-11-05 15:13
Same for me as well sadly

**Comment by wouterdb92** [comment] 2024-11-05 16:04
Same here. Tried to roll back to previous versions. Didn't make a difference, besides it gave a 400 error instead of 412.

**Comment by robwheatley** [comment] 2024-11-05 18:30
Yep, same here - started getting 412 errors about 20 hours ago. Everything is updated to the latest version, but the issue started with an older version (I was hoping that an update would fix the issue).

**Comment by clw123456** [comment] 2024-11-06 06:48
Same issues here sadly

**Comment by 3nigma71** [comment] 2024-11-06 06:53
Mine too only for the last 24 hours

**Comment by ajimix** [comment] 2024-11-07 03:41
You can follow and try to help with [some research here](https://github.com/sockless-coding/panasonic_cc/issues/331)

**Comment by nosek88** [comment] 2024-11-08 10:28
It seems that at HA they have solved the problem
https://github.com/sockless-coding/panasonic_cc/issues/331#issuecomment-2464333592

**Comment by mkz212** [comment] 2024-11-08 14:46
> It seems that at HA they have solved the problem [sockless-coding/panasonic_cc#331 (comment)](https://github.com/sockless-coding/panasonic_cc/issues/331#issuecomment-2464333592)

Yes. Can confirm that Home Assistant Integration works now.

**Comment by nosek88** [comment] 2024-11-08 17:22
Is it possible to transfer the solution from HA to the Homebridge plugin?

**Comment by mkz212** [comment] 2024-11-08 17:24
> Is it possible to transfer the solution from HA to the Homebridge plugin?

Yes, you can make Pull Request.

**Comment by miguelsasso** [comment] 2024-11-08 22:07
> > It seems that at HA they have solved the problem [sockless-coding/panasonic_cc#331 (comment)](https://github.com/sockless-coding/panasonic_cc/issues/331#issuecomment-2464333592)
> 
> Yes. Can confirm that Home Assistant Integration works now.

@mkz212 Are you now using HA for Panasonic units?

**Comment by mkz212** [comment] 2024-11-09 00:36
> > > It seems that at HA they have solved the problem [sockless-coding/panasonic_cc#331 (comment)](https://github.com/sockless-coding/panasonic_cc/issues/331#issuecomment-2464333592)
> > 
> > 
> > Yes. Can confirm that Home Assistant Integration works now.
> 
> @mkz212 Are you now using HA for Panasonic units?

Yes, using HA. Not only for Panasonic. I do not have Homebridge anymore.

**Comment by miguelsasso** [comment] 2024-11-09 00:43
@mkz212 ok, understood. Just noticed you have updated the front page to state plugin no longer supported. Looks like I’m switching to HA. Thanks for your efforts in maintaining the plugin .

**Comment by nosek88** [comment] 2024-11-09 00:46
> the

Slowly, let's not give up. The solution is available, perhaps an update can be released.

**Comment by miguelsasso** [comment] 2024-11-09 01:35
> > the
> 
> Slowly, let's not give up. The solution is available, perhaps an update can be released.

Are you aware of somebody who is actively trying to fix this plugin ?

**Comment by Bowbee** [comment] 2024-11-09 04:42
Ive started a PR adding the relevant code seen in https://github.com/sockless-coding/panasonic_cc/pull/336/files
I dont have the time or setup right now to test - I may have some free time tomorrow. Any assistance is appreciated.

**Comment by mkz212** [comment] 2024-11-09 05:35
> Ive started a PR adding the relevant code seen in https://github.com/sockless-coding/panasonic_cc/pull/336/files I dont have the time or setup right now to test - I may have some free time tomorrow. Any assistance is appreciated.

Merged. Will release 5.3.0 beta soon. Please test.

**Comment by mkz212** [comment] 2024-11-09 05:37
Test 5.3.0-beta.0

**Comment by Bowbee** [comment] 2024-11-09 05:40
Unfortunately doesnt look like just adding the header fixed it. I will attempt to debug when I have time.

![{0E5977B1-F708-4C66-92A5-38CD4B36845A}](https://github.com/user-attachments/assets/2fc658ca-1f87-49ac-83e2-9ffb7775b371)

**Comment by mkz212** [comment] 2024-11-09 05:45
> Unfortunately doesnt look like just adding the header fixed it. I will attempt to debug when I have time.
> 
> ![{0E5977B1-F708-4C66-92A5-38CD4B36845A}](https://private-user-images.githubusercontent.com/28758481/384580398-2fc658ca-1f87-49ac-83e2-9ffb7775b371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzEzNzQsIm5iZiI6MTczMTEzMTA3NCwicGF0aCI6Ii8yODc1ODQ4MS8zODQ1ODAzOTgtMmZjNjU4Y2EtMWY4Ny00OWFjLTgzZTItOWZmYjc3NzViMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODE2YmUzNjdiZDY1NzllMWRjMGVhOGVkZWVjMTY1ZWNiZWUzYzhlZTI5YjRkY2JlNzBhYTEzY2FmMTMwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TSUiM3FSBUQglHkjtf9ek-sNAyDU6ZccfhN8ltunnn8)
> 
> ![{236D02C9-C5E6-46DE-A16A-4D5B41C26FF5}](https://private-user-images.githubusercontent.com/28758481/384580419-8da9dc75-2373-4d5b-9b0e-0943caf2a73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzEzNzQsIm5iZiI6MTczMTEzMTA3NCwicGF0aCI6Ii8yODc1ODQ4MS8zODQ1ODA0MTktOGRhOWRjNzUtMjM3My00ZDViLTliMGUtMDk0M2NhZjJhNzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMTJiZDA3ODQ3OTEzODQwMDg5MGY5NDRkOTYwMTY2NzJjMmMxMmMyZjU5MDE4MTgyYWI3NWQ2ZTMxZjExZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zc3uEUS4CAkuCEXivQa4Me2uPL3d0pEkuAgAYWafwHc)

Maybe need to be UTC timestamp?: https://github.com/sockless-coding/panasonic_cc/commit/2b5733fc40876119c26b24151373a9bef41a0631

**Comment by mkz212** [comment] 2024-11-09 05:49
> Unfortunately doesnt look like just adding the header fixed it. I will attempt to debug when I have time.
> 
> ![{0E5977B1-F708-4C66-92A5-38CD4B36845A}](https://private-user-images.githubusercontent.com/28758481/384580398-2fc658ca-1f87-49ac-83e2-9ffb7775b371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzE2MDYsIm5iZiI6MTczMTEzMTMwNiwicGF0aCI6Ii8yODc1ODQ4MS8zODQ1ODAzOTgtMmZjNjU4Y2EtMWY4Ny00OWFjLTgzZTItOWZmYjc3NzViMzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMmE1NzcwNDVjOGQwNmZlNzQ4NjQyOGIyOWFjNTk3YzA4NGUzNTQ2MDUxZDEyNzI0YWQwMzEzNGNjNGQ0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EpjVrSKXdic2NHMlO7xuwVlqBF5lFRhtWgxyOD59ei0)
> 
> ![{236D02C9-C5E6-46DE-A16A-4D5B41C26FF5}](https://private-user-images.githubusercontent.com/28758481/384580419-8da9dc75-2373-4d5b-9b0e-0943caf2a73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzE2MDYsIm5iZiI6MTczMTEzMTMwNiwicGF0aCI6Ii8yODc1ODQ4MS8zODQ1ODA0MTktOGRhOWRjNzUtMjM3My00ZDViLTliMGUtMDk0M2NhZjJhNzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA1NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4M2QwNzAxZWIwMDg4OGM5YTUzYjBkNDI4MWZiYTJhYWQ0YmFiYTk1ZDU0YjJmMzkyM2NmNzdiMjY3ZDhkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pINDOHwEegLJ1rRqlqow906IrmzO3UuXjaYH_22fvC8)

Maybe need to be UTC timestamp?: https://github.com/sockless-coding/panasonic_cc/commit/2b5733fc40876119c26b24151373a9bef41a0631 and ms timestamp should be * 1000

**Comment by Bowbee** [comment] 2024-11-09 06:05
You're right. Our timestamp was malformed in both the header and api key generation.
test-login works now. PR on its way.

**Comment by mkz212** [comment] 2024-11-09 06:12
Try 5.3.0-beta.1

**Comment by Bowbee** [comment] 2024-11-09 06:15
Confirmed working! Tested via Apple Home app too, all functional for me.

![{5048DF9A-DABA-4EDE-8332-29375A7ABAE3}](https://github.com/user-attachments/assets/21360ed7-fc75-4b65-a767-78fe7aa748f7)

**Comment by mkz212** [comment] 2024-11-09 06:16
> Confirmed working! Tested via Apple Home app too, all functional for me.
> 
> ![{5048DF9A-DABA-4EDE-8332-29375A7ABAE3}](https://private-user-images.githubusercontent.com/28758481/384582017-21360ed7-fc75-4b65-a767-78fe7aa748f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzMyNTMsIm5iZiI6MTczMTEzMjk1MywicGF0aCI6Ii8yODc1ODQ4MS8zODQ1ODIwMTctMjEzNjBlZDctZmM3NS00YjY1LWE3NjctNzhmZTdhYTc0OGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA2MTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNWI5MTZlYjM0NDRmZTJjNWJmY2NmYzBiZWY1ZGFiMjc2NTYzZjU2OGMyMzI4YTdlZTAzNDE0Mzg4MmIyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7WqgvvVCHU5uIixQxfKPiSh5YGu6E76yNWPfdZqBex0)

Great job! Do you want to join and maintain plugin?

**Comment by Bowbee** [comment] 2024-11-09 06:17
I cant commit, but I will help out when I can

**Comment by mkz212** [comment] 2024-11-09 06:22
Thanx to @Bowbee plugin is working again. 👍

**Closed by mkz212** 2024-11-09 06:22 UTC
