### ISSUE TITLE
Issue with fan mode switch in 4.0.5

### ISSUE THREAD

**Issue by dbonyad** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#379] opened 2024-06-23 22:25 UTC
Hi,

Thanks so much for this platform, I use it daily!!

Please can I make a request to bring back the option to set Auto mode in HomeKit to be the Fan mode on the Panasonic air conditioner? I used to use this and it worked great, I could get the AC to operate in fan mode easily and use automations etc. 

Now in 4.0.5, this has been replaced with the new switch for Fan mode, but it does not work with my AC. I have a Panasonic Etherea 3.5kw CU-Z35XKE. it’s about one year old. When I turn on the option for the Fan mode switch in Homebridge, I can see the new switch in HomeKit under the AC itself, however operating this fan mode switch does not work. The AC operates in whatever mode I have selected in HomeKit (Heat/Cool/Auto) but the fan mode switch is totally ignored whether it is on or off. In the new 4.0.5 I can’t find any way to get the AC into Fan mode from HomeKit.

Can I make a feature request for the old option to associated HomeKit auto mode with the Panansonic fan mode?

Thanks!

**Comment by mkz212** [comment] 2024-06-24 01:57
@dbonyad 

Show me response for this device when it is turned on and when it is turned off. To show response enable debug in Homebridge settings and in plugin settings set logs to all.

**Comment by dbonyad** [comment] 2024-06-24 09:11
Please find below logs as requested. I am turning the Fan mode switch on and off and turning the AC itself on and off to try all situations. At no point does the AC ever enter fan mode:

[24/06/2024, 10:02:14] [Homebridge Panasonic AC Platform] Accessory: setActive() for device 'Hallway'
[24/06/2024, 10:02:14] [Homebridge Panasonic AC Platform] Hallway: set Off
[24/06/2024, 10:02:14] [Homebridge Panasonic AC Platform] Comfort Cloud: sendUpdate() for 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:14] [Homebridge Panasonic AC Platform] {
  "operate": 0
}
[24/06/2024, 10:02:14] [Homebridge Panasonic AC Platform] Hallway: Off
[24/06/2024, 10:02:16] [Homebridge Panasonic AC Platform] Comfort Cloud - setDeviceStatus(): Success
[24/06/2024, 10:02:16] [Homebridge Panasonic AC Platform] { result: 0 }
[24/06/2024, 10:02:22] [Homebridge Panasonic AC Platform] Hallway: refresh status
[24/06/2024, 10:02:22] [Homebridge Panasonic AC Platform] Comfort Cloud: getDeviceStatus() for device GUID 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:23] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for GUID 'CS-Z35XKEW+4886927481': Success
[24/06/2024, 10:02:23] [Homebridge Panasonic AC Platform] {
  timestamp: 1719219739515,
  permission: 3,
  summerHouse: 0,
  iAutoX: false,
  nanoe: true,
  nanoeStandAlone: true,
  autoMode: true,
  heatMode: true,
  fanMode: false,
  dryMode: true,
  coolMode: true,
  ecoNavi: false,
  powerfulMode: true,
  quietMode: true,
  airSwingLR: true,
  autoSwingUD: true,
  ecoFunction: 0,
  temperatureUnit: 0,
  modeAvlList: { autoMode: 1 },
  nanoeList: { visualizationShow: 0 },
  clothesDrying: false,
  insideCleaning: false,
  fireplace: false,
  pairedFlg: false,
  parameters: {
    operate: 0,
    operationMode: 2,
    temperatureSet: 16,
    fanSpeed: 5,
    fanAutoMode: 0,
    airSwingLR: 2,
    airSwingUD: 2,
    ecoMode: 0,
    ecoNavi: 0,
    nanoe: 2,
    lastSettingMode: 0,
    iAuto: 0,
    airDirection: 0,
    insideTemperature: 22,
    outTemperature: 126,
    airQuality: 0,
    ecoFunctionData: 0,
    insideCleaning: 0,
    fireplace: 0
  },
  deviceNanoe: 2
}
[24/06/2024, 10:02:23] [Homebridge Panasonic AC Platform] Hallway: Off, Indoor Temp. 22, Outdoor Temp. not available, Cool Mode, Speed 5.
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Accessory: setTargetHeaterCoolerState() for device 'Hallway'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: Mode Cool
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Comfort Cloud: sendUpdate() for 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] {
  "operate": 1,
  "operationMode": 2
}
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Accessory: setActive() for device 'Hallway'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: set On
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Comfort Cloud: sendUpdate() for 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] {
  "operate": 1
}
[24/06/2024, 10:02:53] [Homebridge Panasonic AC Platform] Hallway: On
[24/06/2024, 10:02:54] [Homebridge Panasonic AC Platform] Comfort Cloud - setDeviceStatus(): Success
[24/06/2024, 10:02:54] [Homebridge Panasonic AC Platform] { result: 0 }
[24/06/2024, 10:02:55] [Homebridge Panasonic AC Platform] Comfort Cloud - setDeviceStatus(): Success
[24/06/2024, 10:02:55] [Homebridge Panasonic AC Platform] { result: 0 }
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Hallway: refresh status
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Comfort Cloud: getDeviceStatus() for device GUID 'CS-Z35XKEW+4886927481'
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Comfort Cloud - getDeviceStatus() for GUID 'CS-Z35XKEW+4886927481': Success
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] {
  timestamp: 1719219776059,
  permission: 3,
  summerHouse: 0,
  iAutoX: false,
  nanoe: true,
  nanoeStandAlone: true,
  autoMode: true,
  heatMode: true,
  fanMode: false,
  dryMode: true,
  coolMode: true,
  ecoNavi: false,
  powerfulMode: true,
  quietMode: true,
  airSwingLR: true,
  autoSwingUD: true,
  ecoFunction: 0,
  temperatureUnit: 0,
  modeAvlList: { autoMode: 1 },
  nanoeList: { visualizationShow: 0 },
  clothesDrying: false,
  insideCleaning: false,
  fireplace: false,
  pairedFlg: false,
  parameters: {
    operate: 1,
    operationMode: 2,
    temperatureSet: 16,
    fanSpeed: 5,
    fanAutoMode: 0,
    airSwingLR: 2,
    airSwingUD: 2,
    ecoMode: 0,
    ecoNavi: 0,
    nanoe: 2,
    lastSettingMode: 0,
    iAuto: 0,
    airDirection: 0,
    insideTemperature: 22,
    outTemperature: 126,
    airQuality: 0,
    ecoFunctionData: 0,
    insideCleaning: 0,
    fireplace: 0
  },
  deviceNanoe: 2,
  visualizationAvlFlg: true,
  simulationShowFlg: true,
  simulationSettingFlg: false
}
[24/06/2024, 10:03:01] [Homebridge Panasonic AC Platform] Hallway: On, Indoor Temp. 22, Outdoor Temp. not available, Cool Mode, Speed 5.

**Comment by mkz212** [comment] 2024-06-24 09:35
This is because response from server shows that your AC doesn't support fan mode: `fanMode: false,`. Eh... Panasonic....

**Comment by dbonyad** [comment] 2024-06-24 09:37
Yeah that's a good point. On Comfort Cloud there is a setting called "Nanoe X" mode, which is basically the same. No active heating or cooling just the fan is on. Also, on the previous version of the plugin, when using the Auto = Fan mode toggle, it did activate a hidden fan mode and it worked fine.

So in this case, it would be fine to operate the "Nanoe X" mode or the hidden fan mode. Does this make sense?

**Comment by dbonyad** [comment] 2024-06-24 09:41
The highlighted mode is basically fan mode

![image](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/61993882/f955f90c-0dff-40b5-b88f-1efcb59ae1ce)

**Comment by mkz212** [comment] 2024-06-24 11:01
@dbonyad Try 4.1.0-beta.1

**Comment by mkz212** [comment] 2024-06-24 11:12
> The highlighted mode is basically fan mode
> 
> ![image](https://private-user-images.githubusercontent.com/61993882/342287586-f955f90c-0dff-40b5-b88f-1efcb59ae1ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjc2MDQsIm5iZiI6MTcxOTIyNzMwNCwicGF0aCI6Ii82MTk5Mzg4Mi8zNDIyODc1ODYtZjk1NWY5MGMtMGRmZi00MGI1LWI4OGYtMWVmY2I1OWFlMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDExMDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZmVlNDIxNzJiOThjMmJiNjQwZmY2NjFmODhjNjIxYmYwZTU4YTk2ZTg3ZmFkOGY2OGE3ZTFiODFkYjU1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XFMlbrCKjET1v2kENrN-cBHyfdGkgA19ZMbk0_fM66s)

I didn't even know that this is Fan Mode. This nomenclature is strange.

**Comment by mkz212** [comment] 2024-06-24 12:00
@dbonyad Try how Fan Mode switch works on 4.1.0-beta

**Comment by dbonyad** [comment] 2024-06-24 17:04
Hi,

Thank you so much, that works really well. So now the fan mode switch overrides whatever mode the AC is set to and will force to Fan mode, great work!

I have to personally say that I think it was much easier to use the homekit Auto mode as Fan mode rather than managing a separate switch and remembering to switch it off etc, the interface for it the switch in the home app is quite clunky, but that's just my view. I would request at least giving the option to people to use Auto mode as Fan mode but what you have done has answered the request of being able to trigger Fan mode from Homekit so thank you again!

**Comment by mkz212** [comment] 2024-06-24 17:17
- You don't have to worry about turning off the fan mode switch, when you set another mode, the switch will turn off by itself automatically.

- Unfortunately, we have no influence on the appearance of Apple Home, you have to write to Apple.

- The problem is that Panasonic has more options than the AC view in Apple Home offers, so the sollution is option to additional switches. It's something people have been asking for for a long time. There are so many different AC configurations that we are not able to provide so many options. Therefore, now everyone can add what they need.

- As for the choice of Auto, here too unfortunately there were problems, because one air conditioning has fan mode and dry mode, the other has only dry mode, and the other has only fan mode or even don't have fan and dry.

- I think that now you are able to set up automation as you need, i.e. turn on fan mode, change mode, etc.

**Comment by dbonyad** [comment] 2024-06-24 17:39
That makes sense. Yes your last comment is true and I can now set up automations with fan mode which is great. 

Re the first comment, I didn’t realise the switch automatically turns itself off, I will try that out. 

Thank you again!

**Comment by mkz212** [comment] 2024-06-24 18:07
It seems to me that what you marked on the screenshot is `nanoeStandAlone: true,` and this is responsible for whether the device has this function. And it is enabled by setting `parameters.operationMode` (auto, heat, cool, dry, fan, nanoe stand alone).

Look here:
https://www.panasonic.com/global/hvac/products/comfort-cloud/how-to-use-comfort-cloud/choose-air-conditioner-operation-mode.html

**Comment by dbonyad** [comment] 2024-06-24 18:30
Sorry I’m not sure I fully understand your message. 

The new Fan switch you have enabled activates a hidden fan mode which is actually not selectable in the Comfort Cloud app.  

This is exactly the same as the Nanoe X mode apart from the marketing term so I’m totally happy with what you have done. See image below, this is from using the new switch. 

![IMG_1503](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/61993882/85390fec-4a3c-4f69-ae1c-7ac294d280fc)

**Comment by mkz212** [comment] 2024-06-24 18:34
> Sorry I’m not sure I fully understand your message.
> 
> The new Fan switch you have enabled activates a hidden fan mode which is actually not selectable in the Comfort Cloud app.
> 
> This is exactly the same as the Nanoe X mode apart from the marketing term so I’m totally happy with what you have done. See image below, this is from using the new switch.
> 
> ![IMG_1503](https://private-user-images.githubusercontent.com/61993882/342453037-85390fec-4a3c-4f69-ae1c-7ac294d280fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTQyMjgsIm5iZiI6MTcxOTI1MzkyOCwicGF0aCI6Ii82MTk5Mzg4Mi8zNDI0NTMwMzctODUzOTBmZWMtNGEzYy00ZjY5LWFlMWMtN2FjMjk0ZDI4MGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE4MzIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlN2MyZjdiNDJjOWJhMDk4NWYzNzcyOTkxOTNhOTEzNjE4NzFjNjUxNzMyODUyYWEwZGM3YTYwNDVhODZiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oku2ZhguEjxqYQQT2BYVce2az-dgb3TYbnMl5_G8gJI)

Hmmm... Strange... for me, it activates the mode marked as Nanoe. And seriously it is hidden?

**Comment by dbonyad** [comment] 2024-06-24 18:38
Yes that is weird. Yes correct the dedicated fan mode can’t be activated by the Comfort cloud app. The app does show it correctly when it is on but you can’t select that mode from Comfort cloud. 

The modes shown in comfort cloud for me are Auto, Heat, Cool, Dry, Nanoe X. 

But since Nanoe X and fan are the same I guess it’s pointless having both in the app?

**Comment by mkz212** [comment] 2024-06-24 18:51
I think that might be that parameters.operationMode = 4 is for Fan Mode, Nanoe Stand Alone Mode and iAutoX Mode, and parameters.lastSettingMode decides which one specifically.

Examples:

Heat, Cool, Dry, Auto mode:
parameters.lastSettingMode = 0

Fan mode:
parameters.operationMode = 4
parameters.lastSettingMode = 1

Nanoe Stand Alone:
parameters.operationMode = 4
parameters.lastSettingMode = 2

**Comment by dbonyad** [comment] 2024-06-24 19:04
Yes I can check that, I’ll let you know. 

I would be happy to use either Fan mode or Nanoe stand alone. I want to be able to activate either mode from HomeKit. The new fan mode switch activates the Fan mode and not Nanoe stand alone. 

So I’m happy to use Nanoe stand alone but how would I activate that from HomeKit?

**Comment by mkz212** [comment] 2024-06-24 19:10
> Yes I can check that, I’ll let you know.
> 
> I would be happy to use either Fan mode or Nanoe stand alone. I want to be able to activate either mode from HomeKit. The new fan mode switch activates the Fan mode and not Nanoe stand alone.
> 
> So I’m happy to use Nanoe stand alone but how would I activate that from HomeKit?

There is no separate switch in HomeKit yet. I mean, you turn on Fan mode and check the log in Homebridge. Then turn on Nanoe Stand Alone (through the Panasonic app) and also see the log. 

And see if my theory is confirmed? For both modes parameters.operationMode = 4, but for Fan Mode parameters.lastSettingMode = 1 and for Nanoe Stand Alone parameters.lastSettingMode = 2. Right?

**Comment by mkz212** [comment] 2024-06-25 08:30
I checked and it is as i suspect. But for some reason, the server does not want to accept parameters.lastSettingMode = 2, i.e. it does not want to turn on Nanoe Stand Alone. But if it is turned on through applications, it is and reads correctly the differences between Fan Mode and Nanoe Stand Alone Mode.

**Comment by dbonyad** [comment] 2024-06-25 09:02
Hey, ah great you beat me to it! That's fine though I can continue to use Fan mode.

**Comment by dbonyad** [comment] 2024-06-25 09:05
I did notice one bug this morning. If you try to enable Fan mode with a Homekit automation, I set the automation to turn AC to ON (any mode/any temperature) and turn on the Fan mode switch all in one automation, it often ignores the Fan mode switch and turns the AC to the mode that was set within Homekit. Then after checking the fan mode switch is still off even after the automation is completed. I guess it depends on the order that Homekit executes the routine.

I have managed to create a workaround automation that turns the AC on, then delay 1 second, then turn fan mode on. It does seem to work at the moment.

**Comment by mkz212** [comment] 2024-06-25 09:07
@nanos Can you help? For some reason server doesn't accept parameters.lastSettingMode . This value Decides whether Fan Mode or Nanoe Stand Alone Mode is enabled. When I set the selected mode in the application, it works and reads correctly, but I can't save this value from HomeKit.

**Comment by mkz212** [comment] 2024-06-25 09:09
> I did notice one bug this morning. If you try to enable Fan mode with a Homekit automation, I set the automation to turn AC to ON (any mode/any temperature) and turn on the Fan mode switch all in one automation, it often ignores the Fan mode switch and turns the AC to the mode that was set within Homekit. Then after checking the fan mode switch is still off even after the automation is completed. I guess it depends on the order that Homekit executes the routine.
> 
> I have managed to create a workaround automation that turns the AC on, then delay 1 second, then turn fan mode on. It does seem to work at the moment.

Show me screenshot of automation. You have 2 actions? One to set on and second to turn on Fan Mode? Fan mode switch turn on AC so why this first action?

**Comment by dbonyad** [comment] 2024-06-25 09:51
> Collaborator

This is the one that doesn't work correctly as the Fan on gets ignored.

![image](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/61993882/d1047ae1-d061-46d0-b1c8-d9d976726a0e)

**Comment by mkz212** [comment] 2024-06-25 10:01
If you want to turn on AC in Fan mode, in your autoamtion just turn on Fan mode switch.

**Comment by nanos** [comment] 2024-06-25 10:20
> @nanos Can you help?

Nope, sorry. No idea what's going on.

**Comment by mkz212** [comment] 2024-06-25 14:35
Please test it. If everything ok, please close the Issue. 👍

**Comment by mkz212** [comment] 2024-06-27 10:27
Version 4.1.0 published. Thanks for your report and help. I also encourage you to report errors and/or suggestions in the future.

**Closed by mkz212** 2024-06-27 10:27 UTC
