### ISSUE TITLE
Impossible to connect 

### ISSUE THREAD

**Issue by M0rT4L13** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#115] opened 2023-12-20 17:38 UTC
Hello ! 

I have this issue since this morning, yesterday the pluggin worked well

![IMG_6071](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/121009175/1f2317d8-7e7a-4b4c-934b-05a11e308a87)

The mail and the password are correct and i try to reconnect my homebridge and account twice.

**Comment by mkz212** [comment] 2023-12-20 17:48
Strange. It works for me without a problem. Both - the plugin and the official application. You have latest plugin version - 1.8.4?

**Comment by M0rT4L13** [comment] 2023-12-20 18:27
> Strange. It works for me without a problem. Both - the plugin and the official application. You have latest plugin version - 1.8.4?

Yes sure, 
![IMG_6072](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/121009175/24eb7f4a-a784-4e0b-b3a1-ccfdb44b73e7)

**Comment by mkz212** [comment] 2023-12-20 18:42
- log in to the Panasonic Comfort Cloud application and see if it works there? And don't you have any new conditions to accept?
- you haven't made any modifications in the plugin code?
- restart your router (to gain a new IP)
- restart Homebridge

**Comment by M0rT4L13** [comment] 2023-12-20 18:46
> * log in to the Panasonic Comfort Cloud application and see if it works there? And don't you have any new conditions to accept?

the app works well, no new conditions to accept

> * you haven't made any modifications in the plugin code? No, i will try to uninstall and install after this message

> * restart your router (to gain a new IP) 
done but same issue
> * restart Homebridge
Done but same issue

**Comment by mkz212** [comment] 2023-12-20 18:54
@M0rT4L13 

- I can assure you that it works for me and it is not a global problem.

- Is Homebridge on the same network as the phone on which you have Panasonic app? Do both connect from the same IP?

- Do you have the same Panasonic ID account on both (I ask because you can have different accounts to control the same AC)

- There were no changes from our side today, no plugin update, etc. Maybe you updated something in Homebridge?

If you can not solve the problem, write more information: what version of homebridge, ui, node? Is it on raspberry, docker or something else? In general, try to give as much detail as possible that you think may be useful.

**Comment by M0rT4L13** [comment] 2023-12-20 19:16
> @M0rT4L13
> 
> * I can assure you that it works for me and it is not a global problem.

i trust you lol


> * Is Homebridge on the same network as the phone on which you have Panasonic app? Do both connect from the same IP?

yes the both are connected on the same IP, i restarted the homebridge and the router but still have the issue.

i uninstalled the pluggin and install it again but nothing works, still the same issue

> * Do you have the same Panasonic ID account on both (I ask because you can have different accounts to control the same AC)

Yes sure


> * There were no changes from our side today, no plugin update, etc. Maybe you updated something in Homebridge?

No update, nothing change, the pluggin worked well since the last update 


> If you can not solve the problem, write more information: what version of homebridge, ui, node? Is it on raspberry, docker or something else? In general, try to give as much detail as possible that you think may be useful.

Last homebridge version
Raspberry 

i really don’t know why this is happening :/

**Comment by mkz212** [comment] 2023-12-21 04:56
Can you enable debug mode (in plugin settings and in homebridge settings)? Then you have more logs.

**Comment by M0rT4L13** [comment] 2023-12-22 19:36
OK, problem solved

i just deleted my panasonic ID and recreated a new one. It works.

i don’t know how this happened but nvm, now it works.

Thanks for the help ;)

**Comment by mkz212** [comment] 2023-12-22 19:40
@M0rT4L13 I am glad that the problem is solved. Close the Issue please.

**Closed** 2023-12-22 19:48 UTC
